package comm;
// Generated Jul 20, 2019 3:30:31 PM by Hibernate Tools 4.3.1

import java.util.Iterator;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;




/**
 * App generated by hbm2java
 */
public class App  implements java.io.Serializable {


     private String contact;
     private String name;
     private String age;
     private String symptoms;

    public App() {
    }

	
    public App(String contact) {
        this.contact = contact;
    }
    public App(String contact, String name, String age, String symptoms) {
       this.contact = contact;
       this.name = name;
       this.age = age;
       this.symptoms = symptoms;
    }
   
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getSymptoms() {
        return this.symptoms;
    }
    
    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }


      public String data()
    {
                Configuration cfg = new Configuration();
                cfg.configure("hibernate.cfg.xml");
                SessionFactory sf = cfg.buildSessionFactory();
                Session s = sf.openSession();
                Transaction t = s.beginTransaction();
                Query query = s.createQuery("FROM App");
                List result=query.list();
                Iterator it=result.iterator();
                while(it.hasNext())//for(Iterator itr=result.iterator();itr.hasNext();)
                {
                
                    App a=(App)it.next();
                    
                    System.out.println("name is "+a.getName());
                    a.name= name; 
                    a.age=age;
                    a.symptoms=symptoms;
                    a.contact=contact;
                   
                    
                  return "patientdetails2.xhtml";
                }
               
           return "";      
    } 


}


